### ISSUE TITLE
Support drag/drop of assets from asset selector to Word/Gdoc

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/franklin-assets-selector#55]
Currently Copy/paste via Clipboard API works on selecting an asset in the selector and then pasting it on the Word doc. This ticket is logged to explore if drag/drop can be used as it provides a better user experience.

[Related conversation](https://cq-dev.slack.com/archives/C01RNQM16MP/p1692331630178359)

**Comment by badvision** [comment]
Findings to date:
- Iframes in the same window from different domains cannot send or receive drag events from each other.  There's no way to get around this easily.
- When the Franklin sidekick plugin injects its html, the browser treats the html/javascript as being from the domain of the origin homepage.
- One thing worth investigating is to inject the franklin sidekick into the word document iframe instead of the top-level iframe -- this might work (?)
- Another possibility is a browser-side proxy but that is likely to be very fragile and/or introduce a lot of complexity.

It is worth noting that drag-drop between windows works fine with no changes.  I haven't tried any other alternatives such as frames.

**Comment by tmathern** [comment]
Closing this for now, as we're going another way. (We can reopen if needed).
